### PR TITLE
Added Navbar

### LINKED ISSUE #5: Feat : Navbar
should be reponsive and modern ( can make use of shadcn)
should contain a logo (will provide) at left and at rightside a button (clerk) and routes

### PR DESCRIPTION
**Pull request by nithinrvs**
### Description
Added Navbar with three routes (Home, Notes, Daily quotes). Below is the screenshot:
image

### Related Issue
Fixes #5 

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [  x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by TenzDelek** [comment]
lgtm thanks @nithinrvs

**Comment by TenzDelek** [comment]
resolve the conflict and we can merged it, just copy and paste the new package.json and lock 
cc. @nithinrvs

**Comment by nithinrvs** [comment]
@TenzDelek cab you please check now?

**Comment by TenzDelek** [comment]
lgtm

**Pull request merged**
