### PR TITLE
Feat/prisma supabase setup

### LINKED ISSUE #6: Feat : supabase and prisma setup
set up supabase and prisma

### PR DESCRIPTION
**Pull request by Abhi0049k**
### Description
This pull request introduces Supabase and Prisma to DearDiary, enhancing our database management capabilities and providing a robust ORM for efficient data operations.

### Changes Made
- Added Prisma and Supabase client dependencies
- Initialized Prisma in the project
- Created Prisma schema for the Diary model
- Set up Prisma client instance for database operations
- Configured Supabase client for additional features
- Updated environment variables to include Supabase and database connection details

### Related Issue
Fixes #6 

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Abhi0049k** [comment]
@TenzDelek , I have raised a PR based on our previous discussion, but the Notion document is still not accessible.
image

**Comment by TenzDelek** [comment]
image
@Abhi0049k  make the setup as per the setup send here. something wrong with my notion access. so sending the capture.
if need help ping me

**Comment by Abhi0049k** [comment]
Thank you, @TenzDelek , for the screenshot. I have made the changes accordingly. Please let me know if there is anything else I need to do."

**Comment by TenzDelek** [comment]
LGTM

**Pull request merged**
