### PR TITLE
Error 404 page created for dear diary.

### LINKED ISSUE #132: Designing a custom error 404 page
#### Description
The current 404 error page does not provide an optimal user experience, especially in a production environment. A well-designed custom 404 page can enhance the overall aesthetic and usability of the site.

#### Proposed Solution
I propose to design a custom 404 error page that aligns with the site's branding and improves user engagement. 

#### Plan
1. **Labeling**: Please assign the issue the GSSOC-ext and Hacktoberfest and level labels.
2. **Wireframe**: I will share a wireframe within the first hour of being assigned to the issue.
3. **Approval**: Upon receiving approval for the wireframe, I will start the design process.
4. **Completion**: The design will be completed within 24 hours of wireframe approval.

#### Benefits
- Improved user experience and site navigation.
- Enhanced branding consistency.
- Potential reduction in bounce rates.

I look forward to your feedback and hope to contribute positively to the project!

### PR DESCRIPTION
**Pull request by dev129**
**Title**:  
`[Fix] 404 Page with Light/Dark Mode Support and Framer Motion Animations`

---

### Description
This PR introduces a 404 error page using **Framer Motion** for smooth animations, and it is fully adaptive to changes in light and dark mode. The motivation behind this PR is to enhance user experience by providing a sleek, animated error page that integrates seamlessly with the system’s theme settings.

This PR addresses the **404 error page** feature requested in issue  #132 .

---

### Related Issue
Fixes #132

---

### Type of Change
- [x] New feature (non-breaking change which adds functionality)

---

### Checklist
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas (e.g., dark/light mode logic).
- [x] I have added tests that prove my feature works (manual testing for light/dark mode and responsiveness).
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

---

### Additional Notes for the Reviewer:
**@TenzDelek**, please update the `package.json` and `package-lock.json` to include configurations that support cross-environment development (`cross-env`). I didn’t make these changes because I’m still a beginner and wanted to avoid potential merge conflicts with other ongoing work.

### CODE REVIEW

**Comment by dev129** [comment]
Hey @TenzDelek , I have just launched the PR , kindly review it.

**Comment by dev129** [comment]
Hi @TenzDelek please review my PR and merge it.

**Comment by dev129** [comment]
Hi @TenzDelek , please review and ad my PR.

**Comment by dev129** [comment]
@TenzDelek please review my PR, the leaderboard is to be updated.

**Comment by TenzDelek** [comment]
lgtm

**Pull request merged**
