### PR TITLE
set up supabase/prima and create guestbook

### LINKED ISSUE #37: Feat: create guestbook
take inspiration from this site : https://www.knlrvr.dev/guestbook
https://bejamas.io/hub/guides/how-to-create-a-guestbook

### PR DESCRIPTION
**Pull request by mchen610**
### Description
This PR introduces the guestbook feature and integrates it with Supabase and Prisma. I have set up the database with two main tables: `user` and `guestbook`. The user authentication and management are handled using Clerk, which ensures secure and smooth authentication for guestbook entries. The guestbook allows users to submit messages, which are stored in the database, and all entries are fetched and displayed on the page.

### Related Issue
Fixes #37

### Type of change
- [x] New feature (non-breaking change which adds functionality)

### Motivation
The motivation behind this PR is to implement a fully functional guestbook, allowing authenticated users to sign the guestbook. Integrating Supabase/Prisma and Clerk ensures a seamless and secure experience for storing and retrieving guestbook entries.

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

This PR delivers a user-friendly guestbook feature integrated with Clerk for authentication and Supabase/Prisma for data persistence.

### CODE REVIEW

**Comment by mchen610** [comment]
Requires running:

```
npx prisma generate
npx prisma db push
npx prisma studio
```

**Comment by TenzDelek** [comment]
@mchen610  can you share a screen recording or a screenshot of the demo.

**Comment by mchen610** [comment]
https://www.youtube.com/watch?v=ojtCEMS80XQ @TenzDelek

**Comment by TenzDelek** [comment]
> https://www.youtube.com/watch?v=ojtCEMS80XQ @TenzDelek

it doesnt show the guestbook part, maybe it was trim. can you look at it. cc @mchen610 
you can share a screenshot of the page if it is more convenient  to you

**Comment by mchen610** [comment]
@TenzDelek Sorry I posted the wrong video on accident, here: https://www.youtube.com/watch?v=UrqDj90_tDc. Also what should I do about the package-lock.json conflict?

**Comment by TenzDelek** [comment]
you can just delete the package-lock and copy the one in the github, its easiest way to solve it 
cc @mchen610

**Comment by TenzDelek** [comment]
i saw the demo and it looks great, fix the conflict and it is ready to merge  @mchen610

**Comment by TenzDelek** [comment]
LGTM CC @mchen610

**Pull request merged**
