### PR TITLE
personalized daily quote section by adding different categories

### LINKED ISSUE #49: Inspirational Quotes Feature
I want to implement a feature that suggests quotes or prompts to inspire users when they're unsure what to write about.
how i can i implement it

### LINKED ISSUE #162: Feature Request: Quote of the Day Customization
#### Description
Allow users to personalize the "Quote of the Day" feature by selecting from different categories (e.g., motivational, reflective). This feature will give users a tailored and inspiring journaling experience.

#### Proposed Features
- **Category Selection:** Users can select a theme for their daily quotes, like "motivational," "reflective," or "gratitude."
- **Custom Quotes:** Allow users to add their own favorite quotes to display in the "Quote of the Day" section.

#### Tasks
1. **UI Update:** Create an interface for users to select quote categories or add custom quotes.
2. **Quote Database:** Implement a backend system to store and categorize quotes.
3. **Daily Display:** Ensure the selected or custom quote appears daily on the user's dashboard.

#### Benefits
- Provides a personalized, motivating experience for users.
- Increases user engagement by letting them see quotes that resonate with them.

---

**Please assign this issue to GSSoC'24 ext and Hacktoberfest labels.**

### PR DESCRIPTION
**Pull request by sezallagwal**
### Description
Please include a summary of the changes and the related issue. Also, explain the motivation behind this PR.

### Related Issue
Fixes #162 
fixes #49 

https://github.com/user-attachments/assets/cb213c9c-578e-4827-8429-2394df1da600

@TenzDelek please review this pr thanks!

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by TenzDelek** [comment]
fix the conflict and it is ready to merge

**Comment by sezallagwal** [comment]
@TenzDelek please merge this pr and assign @amitb0ra with appropriate level

**Comment by sezallagwal** [comment]
@sezallagwal @sanjay-kv any updates?

**Comment by sezallagwal** [comment]
@sanjay-kv @TenzDelek any updates?

**Pull request closed without merging**
