### PR TITLE
Added a Rating Popup

### LINKED ISSUE #133: Adding a Rate Us section
### Is your proposal related to a problem?

There is no rate us section in this website.

### Describe the solution you'd like

We can add a feature of rate us which will be in a form of dialog box which pops up after 20 seconds of the user being on the website. This will allow us to get the user input.

### PR DESCRIPTION
**Pull request by SrishtiChamoli**
### Description
I have implemented a rating pop-up feature that activates 15 seconds after a user arrives on the homepage. This functionality enables us to gather valuable user feedback in the form of star ratings and comments, contributing significantly to the maintenance of our user database. After submitting their feedback, users will see a 'Thank you for your feedback' message displayed for 3 seconds, enhancing their experience and engagement.

### Related Issue
Fixes #133 

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by SrishtiChamoli** [comment]
> ### Description
> I have implemented a rating pop-up feature that activates 15 seconds after a user arrives on the homepage. This functionality enables us to gather valuable user feedback in the form of star ratings and comments, contributing significantly to the maintenance of our user database. After submitting their feedback, users will see a 'Thank you for your feedback' message displayed for 3 seconds, enhancing their experience and engagement.
> 
> ### Related Issue
> Fixes #133
> 
> ### Type of change
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> 
> ### Checklist
> * [x]  My code follows the style guidelines of this project
> * [x]  I have performed a self-review of my own code
> * [x]  I have commented on my code, particularly in hard-to-understand areas
> * [x]  I have added tests that prove my fix is effective or that my feature works
> * [x]  New and existing unit tests pass locally with my changes
> * [x]  Any dependent changes have been merged and published in downstream modules

ratinggg
ratinggg1

**Comment by SrishtiChamoli** [comment]
Hey @TenzDelek Ive launched a PR. Please review it once!

**Comment by SrishtiChamoli** [comment]
I have integrated Tailwind CSS in the review component and got rid of the CSS file to make it more consistent across the platform. Please review it once.

**Comment by TenzDelek** [comment]
lgtm

**Pull request merged**
