### PR TITLE
added theme toggler

### LINKED ISSUE #32: Feat : dark mode and light mode
should be functional across all page and support tailwind
use contextapi or redux or any other state management

### PR DESCRIPTION
**Pull request by Sourabh782**
### Description
Added light dark theme toggler

### Related Issue
Fixes #32 

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by TenzDelek** [comment]
resolve the conflict and it LGTM

**Comment by Sourabh782** [comment]
@TenzDelek working on it

**Comment by Sourabh782** [comment]
@TenzDelek can you help me with an issue?

**Comment by Sourabh782** [comment]
@TenzDelek Can you ckeck?

**Comment by TenzDelek** [comment]
LGTM cc @Sourabh782

**Pull request merged**
