### PR TITLE
bugfix/correct-favicon-location

### LINKED ISSUE #68: Bug: place the favicon.io to correct structure
the current favicon is at public which is wrong. put that in correct place (should be in the app dir)
> encourage a new comer to do this

### PR DESCRIPTION
**Pull request by harish08102004**
### Description
This pull request fixes the incorrect path for the favicon in the project. The `favicon.ico` file was already located in the `public` directory, but the code referencing it had an incorrect path.

### Changes Made
- Corrected the path to the `favicon.ico` file in the application code to properly point to `public/favicon.ico`.

### Closed 
#68

### CODE REVIEW

**Comment by TenzDelek** [comment]
can you share a screenshot of the working webapp

**Comment by harish08102004** [comment]
@TenzDelek 
I haven't got any errors till now after changing those paths.
image
image

**Comment by TenzDelek** [comment]
the favicon is still not visible. just put the favicon to app folder and check

**Comment by harish08102004** [comment]
oh I will check that.

**Comment by TenzDelek** [comment]
image

**Comment by harish08102004** [comment]
Hey it is now showing.

**Comment by TenzDelek** [comment]
check the preview , if you can see the favicon there then will merge it.

**Comment by harish08102004** [comment]
image

I copied the logo image and pasted it on the issue page, which generated a link for the image. After that, it worked.

Is this a recommended method?

Should I now add the image link to the .env file and then provide a path to it?

**Comment by TenzDelek** [comment]
lgtm!

**Comment by harish08102004** [comment]
Hey @TenzDelek I have put so much time solving this, can you make this PR as level 2 if possible ?

**Comment by TenzDelek** [comment]
Hey @harish08102004 , sorry but project admins are specifically told to be strict about the level assigning , and this pr to Change a location doesn't seem to be a level 2 worth. Hope you understand . 
Cc @MastanSayyad @sanjay-kv

**Comment by harish08102004** [comment]
ok no issues.

**Pull request merged**
