### PR TITLE
home page UI enhanced with framer motion

### PR DESCRIPTION
**Pull request by inkerton**
### Description
I have change the home page UI to match the theme of About page and Daily Quotes Page also added framer motion's animation to the components.

### Related Issue
Fixes # (issue) #94 

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by inkerton** [comment]
https://github.com/user-attachments/assets/8520c9fe-9c77-41c3-9350-52be8711013d

**Comment by inkerton** [comment]
@TenzDelek Hi have a look at the PR and the changes and let me know.

**Comment by inkerton** [comment]
Also I saw that you assigned the backend for notes page and the designing of notes page to 2 others. Have they worked  on it then I would like to work on a profile page. 

If you have any other issue level2 or level3 then let me know. I would be happy to contribute.
@TenzDelek

**Comment by TenzDelek** [comment]
@inkerton  i think you have misunderstood the assignment,  you have to match the other two to match the home page not the way around !!

**Comment by inkerton** [comment]
@TenzDelek  
Do you want me to remove the framer motion animations and make both the pages resemble the original home page black and white ???

**Comment by TenzDelek** [comment]
> @TenzDelek Do you want me to remove the framer motion animations and make both the pages resemble the original home page black and white ???

yes ,  check the issue card once and use that hex colour

**Comment by inkerton** [comment]
ok I'll do it @TenzDelek . 
My bad I thought you wanted to UI of home page to be changed.

**Comment by inkerton** [comment]
image

This is what You want right???
@TenzDelek

**Comment by inkerton** [comment]
image

**Comment by inkerton** [comment]
@TenzDelek

**Comment by TenzDelek** [comment]
All the pages are updated right? I am out of station so I can't check rn. Will merge if all pages have been changed

**Comment by inkerton** [comment]
@TenzDelek Ok i commited all pages their is some issue in the daily quotes page send me the screenshot please and i will resolve it and make a final commit

**Comment by TenzDelek** [comment]
make the file from js to jsx. it should solve the conflict

**Comment by inkerton** [comment]
@TenzDelek All done you should be able to merge them now.

**Comment by TenzDelek** [comment]
lgtm, i will remove the quote error

**Pull request merged**
