### PR TITLE
Adding diary page to perform crud operation

### LINKED ISSUE #7: Feat : Creating a Diary page
create a page where we can write diary (crud) 
will discuss later about design and overview when assign is finish

### PR DESCRIPTION
**Pull request by Abhi0049k**
### Description
This PR introduces a new page that allows users to perform CRUD (Create, Read, Update, Delete) operations for diary entries. The implementation focuses on creating a user-friendly interface to manage diary entries effectively.

### Features Added:
- Create Diary Entry: Users can add new diary entries through a form interface, including fields for title and content.
- Read Diary Entries: All diary entries are displayed in a list format, allowing users to view their entries at a glance.
- Update Diary Entry: Users can edit existing diary entries through a modal that populates with the current entry data for easy modification.
- Delete Diary Entry: Users have the option to delete diary entries, ensuring they can manage their entries as needed.

### Related Issue
Fixes #7 

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Abhi0049k** [comment]
Hi @TenzDelek, pr daily page

**Comment by TenzDelek** [comment]
Hey , I will of out of station till tomorrow, in the meantime, share a demo

**Comment by Abhi0049k** [comment]
@TenzDelek okay got it

**Comment by Abhi0049k** [comment]
https://github.com/user-attachments/assets/f6d2c7b9-ab9c-4378-bf46-607ccd1affb2

route: /diary

**Comment by Abhi0049k** [comment]
Hi @TenzDelek, here is the demo:

https://github.com/user-attachments/assets/e9337096-10aa-4f93-b99c-ed9e5e92ab95

route: /diary

**Comment by TenzDelek** [comment]
lgtm!

**Pull request merged**
